name: Matrix YouTube Transcription

on:
  workflow_dispatch:
  push: 

jobs:
    transcribing:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        
        - uses: prefix-dev/setup-pixi@v0.9.4
          with:
            cache: true
            cache-write: ${{ github.event_name == 'push' && github.ref_name == 'main' }}

        - name: setup firefox for simulation
          run: |
            sudo snap install firefox
            firefox -headless -CreateProfile "default" || true
            timeout --preserve-status 5s firefox -headless -P "default" "https://www.youtube.com/" || true
            timeout --preserve-status 10s firefox -headless -P "default" "https://www.youtube.com/results?search_query=castle%20on%20the%20hill" || true
            timeout --preserve-status 30s firefox -headless -P "default" "https://www.youtube.com/watch?v=K0ibBPhiaG0" || true
    
        - name: Transcribe
          run: |
            yes | pixi run python batch_transcribe_all_videos.py
            
        - name: Bump version and push tag
          id: tag_version
          uses: mathieudutour/github-tag-action@v6.2
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
    
        - name: Create a new release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: ${{ steps.tag_version.outputs.new_tag }}
            make_latest: true
            generate_release_notes: true
            fail_on_unmatched_files: false
            prerelease: false
            files: |
              output/*
